// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/login","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"Trang Chủ","path":"","parentId":"4","id":"3","originPath":"/home"},"4":{"path":"/home","isWrapper":true,"parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"","name":"Thực đơn","parentId":"6","id":"5","originPath":"/products"},"6":{"path":"/products","isWrapper":true,"parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"","name":"Đăng xuất","parentId":"8","id":"7","originPath":"/logout"},"8":{"path":"/logout","isWrapper":true,"parentId":"ant-design-pro-layout","id":"8"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "wrappers__auth" */'@/wrappers/auth.js')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Products__index" */'@/pages/Products/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "wrappers__auth" */'@/wrappers/auth.js')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Logout__index" */'@/pages/Logout/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "wrappers__auth" */'@/wrappers/auth.js')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/tony/Documents/MyApp/umi-dva/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
