// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/tony/Documents/MyApp/umi-dva/src/pages/Admin/model';
import model_2 from '/Users/tony/Documents/MyApp/umi-dva/src/pages/Login/model';
import model_3 from '/Users/tony/Documents/MyApp/umi-dva/src/pages/Products/model';

export const models = {
model_1: { namespace: 'Admin.model', model: model_1 },
model_2: { namespace: 'Login.model', model: model_2 },
model_3: { namespace: 'Products.model', model: model_3 },
} as const
